#!/bin/bash

# Quick Branch Cleanup Guide
# Run this script to see step-by-step instructions

set -e

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

clear

echo -e "${BLUE}╔════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Branch Cleanup Quick Start Guide        ║${NC}"
echo -e "${BLUE}╔════════════════════════════════════════════╗${NC}"
echo ""

echo -e "${GREEN}OBJECTIVE:${NC} Clean up 110+ branches in the repository"
echo -e "${GREEN}APPROACH:${NC} Merge 8 priority branches, delete 50+ obsolete branches"
echo ""

echo -e "${YELLOW}═══════════════════════════════════════════════${NC}"
echo -e "${YELLOW}OPTION 1: GitHub Actions (Easiest)${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════${NC}"
echo ""
echo "1. Go to GitHub Actions tab:"
echo "   https://github.com/oconnorw225-del/Trader-bot-/actions"
echo ""
echo "2. Select 'Branch Cleanup Helper' workflow"
echo ""
echo "3. Click 'Run workflow' and choose action:"
echo "   • list-branches    - See all branches"
echo "   • delete-obsolete  - Delete 50+ obsolete branches"
echo "   • create-merge-prs - Create PRs for 8 priority branches"
echo ""
echo "4. Enable 'dry_run' first to preview"
echo ""
echo "5. Run again without dry_run to execute"
echo ""

echo -e "${YELLOW}═══════════════════════════════════════════════${NC}"
echo -e "${YELLOW}OPTION 2: Manual Script Execution${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════${NC}"
echo ""
echo "If you have GitHub CLI (gh) configured:"
echo ""
echo "  # Delete obsolete branches"
echo "  bash scripts/delete-branches.sh"
echo ""
echo "  # Or generate commands"
echo "  bash scripts/delete-obsolete-branches.sh"
echo ""

echo -e "${YELLOW}═══════════════════════════════════════════════${NC}"
echo -e "${YELLOW}OPTION 3: GitHub Web Interface${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════${NC}"
echo ""
echo "For each priority branch:"
echo ""
echo "1. Go to: https://github.com/oconnorw225-del/Trader-bot-/compare"
echo ""
echo "2. Select base: main, compare: BRANCH_NAME"
echo ""
echo "3. Create Pull Request"
echo ""
echo "4. Resolve conflicts in GitHub's editor"
echo ""
echo "5. Merge when ready"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════${NC}"
echo -e "${BLUE}8 PRIORITY BRANCHES TO MERGE:${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════${NC}"
echo ""
echo "  1. fix/lint-and-tests (code quality foundation)"
echo "  2. feature/auto-start-system"
echo "  3. copilot/configure-copilot-instructions"
echo "  4. copilot/fix-ci-cd-workflow-issues"
echo "  5. copilot/add-autostart-system-features"
echo "  6. feature/autonomous-job-automation-complete"
echo "  7. copilot/consolidate-mobile-styles"
echo "  8. copilot/add-todo-list-feature"
echo ""

echo -e "${RED}═══════════════════════════════════════════════${NC}"
echo -e "${RED}50+ BRANCHES TO DELETE:${NC}"
echo -e "${RED}═══════════════════════════════════════════════${NC}"
echo ""
echo "  • 3 duplicate branches"
echo "  • 4 setup branches (already applied)"
echo "  • 10 completed work branches"
echo "  • 5 configuration branches"
echo "  • 28 autopilot fix branches"
echo "  • 6+ miscellaneous branches"
echo ""
echo "  Full list in: BRANCH_MERGE_PLAN.md"
echo ""

echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo -e "${GREEN}SAFETY FEATURES:${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo ""
echo "  ✓ Backup tags created automatically"
echo "  ✓ Dry-run mode available"
echo "  ✓ All operations are reversible"
echo "  ✓ No force operations"
echo "  ✓ Conflict detection"
echo ""

echo -e "${YELLOW}═══════════════════════════════════════════════${NC}"
echo -e "${YELLOW}RECOMMENDED WORKFLOW:${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════${NC}"
echo ""
echo "  Step 1: Review documentation"
echo "          → Read BRANCH_CLEANUP_SUMMARY.md"
echo ""
echo "  Step 2: Test in dry-run mode"
echo "          → Run GitHub Actions with dry_run=true"
echo ""
echo "  Step 3: Create merge PRs"
echo "          → Use GitHub Actions or web interface"
echo ""
echo "  Step 4: Review and merge PRs"
echo "          → One at a time, resolve conflicts"
echo ""
echo "  Step 5: Delete obsolete branches"
echo "          → Run deletion script or workflow"
echo ""
echo "  Step 6: Verify results"
echo "          → Check branch count reduced to ~10-15"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════${NC}"
echo -e "${BLUE}DOCUMENTATION:${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════${NC}"
echo ""
echo "  • BRANCH_CLEANUP_SUMMARY.md  - Quick overview (7KB)"
echo "  • BRANCH_MERGE_PLAN.md       - Detailed plan (8KB)"
echo "  • BRANCH_CLEANUP_GUIDE.md    - Existing guide"
echo "  • scripts/                   - Automation scripts"
echo ""

echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo -e "${GREEN}EXPECTED RESULTS:${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo ""
echo "  Before: 110+ branches"
echo "  After:  10-15 branches"
echo "  Reduction: 85-90%"
echo ""
echo "  ✓ Clean repository structure"
echo "  ✓ Easy navigation"
echo "  ✓ Faster operations"
echo "  ✓ All features preserved"
echo ""

echo -e "${YELLOW}═══════════════════════════════════════════════${NC}"
echo -e "${YELLOW}NEED HELP?${NC}"
echo -e "${YELLOW}═══════════════════════════════════════════════${NC}"
echo ""
echo "  • Read the full documentation in BRANCH_MERGE_PLAN.md"
echo "  • Check existing scripts in scripts/ directory"
echo "  • Review workflow file: .github/workflows/branch-cleanup.yml"
echo ""

echo -e "${BLUE}╚════════════════════════════════════════════╝${NC}"
echo ""
